services:
  traefik:
    image: traefik:latest
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --accesslog=true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  traefik-forward-auth:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    container_name: oauth2_proxy
    command: >-
     #--allowed-role=EXLIQUID
      --auth-logging=true
     --whitelist-domain=${GUI_HOST}
     --http-address="0.0.0.0:4180"
     --reverse-proxy=true
     --upstream="static://202"
     --email-domain="*"
     --cookie-name="_samplelocator_oauth2"
     --cookie-secret="${AUTHENTICATION_SECRET}"
     --cookie-expire="12h"
     --cookie-secure="true"
     --cookie-httponly="true"
     #OIDC settings
     --provider="oidc"
     --provider-display-name="LifeScience AAI"
     --client-id="${OAUTH_CLIENT_ID}"
     --client-secret="${OAUTH_CLIENT_SECRET}"
     --redirect-url="https://${GUI_HOST}/_oauth/callback"
     --oidc-issuer-url="${OAUTH_ISSUER_URL}"
     --scope="openid email profile"
     --code-challenge-method="S256"
     --skip-provider-button=true
     --proxy-prefix=/_oauth
     #X-Forwarded-Header settings - true/false depending on your needs
     --pass-basic-auth=true
     --pass-user-headers=false
     --pass-access-token=true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-forward-auth.rule=Host(`${GUI_HOST}`) && PathPrefix(`/_oauth`)"
      - "traefik.http.services.traefik-forward-auth.loadbalancer.server.port=4180"
      - "traefik.http.routers.traefik-forward-auth.tls=true"
    restart: unless-stopped
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}

  lens:
    image: samply/gbn-sample-locator:main
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lens.rule=Host(`${GUI_HOST}`)"
      - "traefik.http.routers.lens.tls=true"
      - "traefik.http.routers.lens.middlewares=traefik-forward-auth"

  spot:
    image: samply/rustyspot:main
    platform: linux/amd64
    ports:
      - "8055:8055"
    environment:
      HTTP_PROXY: ${http_proxy}
      HTTPS_PROXY: ${https_proxy}
      NO_PROXY: beam-proxy
      BEAM_SECRET: "${LOCAL_BEAM_SECRET_SPOT}"
      BEAM_PROXY_URL: http://beam-proxy:8081
      BEAM_APP_ID: "spot.${LOCAL_BEAM_ID}.${BROKER_HOST}"
      CORS_ORIGIN: "https://${GUI_HOST}"
      BIND_ADDR: 0.0.0.0:8055
      RUST_LOG: "info"
      LOG_FILE: /logs/requests.log
    volumes:
      - ./logs:/logs
    depends_on:
      - "beam-proxy"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.spot.loadbalancer.server.port=8055"
      - "traefik.http.middlewares.corsheaders.headers.accesscontrolallowmethods=GET,OPTIONS,POST"
      - "traefik.http.middlewares.corsheaders.headers.accesscontrolallowheaders=content-type"
      - "traefik.http.middlewares.corsheaders.headers.accesscontrolalloworiginlist=https://${GUI_HOST}"
      - "traefik.http.middlewares.corsheaders.headers.accesscontrolallowcredentials=true"
      - "traefik.http.middlewares.corsheaders.headers.accesscontrolmaxage=-1"
      - "traefik.http.routers.spot.rule=Host(`backend.${GUI_HOST}`) && PathPrefix(`/prod`)"
      - "traefik.http.middlewares.stripprefix_spot_prod.stripprefix.prefixes=/prod"
      - "traefik.http.routers.spot.tls=true"
      - "traefik.http.routers.spot.middlewares=corsheaders,traefik-forward-auth,stripprefix_spot_prod"

  beam-proxy:
    image: docker.verbis.dkfz.de/cache/samply/beam-proxy:develop
    platform: linux/amd64
    environment:
      BROKER_URL: https://${BROKER_HOST}
      PROXY_ID: ${LOCAL_BEAM_ID}.${BROKER_HOST}
      APP_spot_KEY: ${LOCAL_BEAM_SECRET_SPOT}
      PRIVKEY_FILE: /run/secrets/proxy.pem
      ALL_PROXY: ${http_proxy}
    secrets:
      - proxy.pem
      - root.crt.pem

secrets:
  proxy.pem:
    file: /etc/lens/pki/${LOCAL_BEAM_ID}.priv.pem
  root.crt.pem:
    file: ./rootcerts/root.crt.pem
